/*******************************************************************************
 * Macro Name: Macro1
 * Creator  : 
 *
 * Revision History:
 * 29 Nov 2022	Generated by L-Edit
 *******************************************************************************/
#include <cstdlib>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <cctype>
#include <cmath>

#include <string>

#define EXCLUDE_LEDIT_LEGACY_UPI

#include <ldata.h>


extern "C" {
	void OpenGDSII(void);
	int UPI_Entry_Point(void);
}

void OpenGDSII(void)
{
	//LCell	pCell	=	LCell_GetVisible();
	//LFile	pFile	=	LCell_GetFile(pCell);
	
	char DesignFileName[] = "tmpdesign.tdb";
	LFile pFile = LFile_New( NULL, DesignFileName );
	
	char pcszSrcFile[] = "F:\\ant1_lvs.gds"; 
	LBoolean bUseGDSDataType = LTRUE; 
	LOverwriteCellsScopeOnImport OverwriteCells = cOverwriteAllCells; 
	LBoolean bGdsFileResolution = LTRUE; 
	double dCustomResolution = 0; 
	const char pcszLogFileName[] = "GDSII_import_log"; 

	LFile_ImportGDSII( pFile, pcszSrcFile, bUseGDSDataType,  OverwriteCells,  bGdsFileResolution, dCustomResolution,  pcszLogFileName);

}

int UPI_Entry_Point(void)
{
	LMacro_BindToMenuAndHotKey_v9_30("Tools", NULL /*hotkey*/, 
			"OpenGDSII", "OpenGDSII", NULL /*hotkey category*/);
	return 1;
}
